### ISSUE TITLE
Upgrade test project and switch to xUnit

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#101]
The test project is using an unsupported .NET version. Upgrade to .NET 6 and switch the test runner to xUnit.

**Comment by mattherman** [comment]
The project was updated to .NET 6 in #105. It still needs to be migrated to xUnit at some point.

**Comment by roundrobinquantum** [comment]
Hello @mattherman here is my pr for migrated xUnit solution => https://github.com/mattherman/MbDotNet/pull/135
