### ISSUE TITLE
Delete Imposters By Name

### ISSUE THREAD

**Issue by rsr-maersk** [mattherman/MbDotNet#134]
Hi. Greate package thank you!!!

Now that we can create imposters by name, would it be possible to delete them by name also?
Ie. same instance, same port, multiple named imposters, but delete only 1 of them?

```c#
public async Task<HttpImposter> CreateHttpImposterAsync(
  int? port,
  string name,
  Action<HttpImposter> imposterConfigurator,
  CancellationToken cancellationToken = default (CancellationToken))
```

**Comment by roundrobinquantum** [comment]
Hello @rsr-maersk you can't create multiple named imposters in same port, so deleting by port number will also remove desired named imposter
