### ISSUE TITLE
DAMP versus DRY in Acceptance Tests

### ISSUE THREAD

**Issue by nrjohnstone** [mattherman/MbDotNet#17]
I have no where else to raise or discuss this with you so I'll need to raise it as an issue here

Tests should be DAMP where possible to aid in understanding, not DRY. 

There is no point moving the private methods that "seem" to be repeated code among the tests are they are merely a means of fluently expressing the intent of the public method by keeping all of the statements at the same abstraction level.

**Comment by mattherman** [comment]
Fair enough. I see your point.
