### ISSUE TITLE
Mock verification property "numberOfRequests" is broken

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#19]
The NumberOfRequests property on RetrievedImposter does not get set properly. When debugging the acceptance tests I noticed it was not returned by mountebank when the GET imposter call was made.

**Comment by nrjohnstone** [comment]
The number of requests property will only get set if you are running with --mock enabled for mountebank, otherwise it will always return zero

**Comment by nrjohnstone** [comment]
use the docker compose file i have created, this will start mountebank with the --mocks parameter and then run the integration tests...

To use the docker compose file, change to the folder with the file and type "docker-compose up"

**Comment by mattherman** [comment]
I ran mountebank using the following command: ``` mb --mock ```
When I ran the acceptance test and inspected the content of the response, I did not have the numberOfRequests property.

I tried starting mountebank via docker-compose and that worked as you said it would. What is that doing that is different from me running mountebank directly with the ```--mock``` flag?

**Comment by nrjohnstone** [comment]
not sure, if you look in the docker directory at the build file, mountebank is started with mock and start command

mb start --mock

is that what you are doing?
Also, which version are you running locally of mb?
