### ISSUE TITLE
Reject HTTPS imposters with invalid key/cert

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#28]
Mountebank requires the key and cert of an HTTPS imposter to be a valid PEM-formatted string. While the docs for the `CreateHttpsImposter` method call this out, the method does not do any validation. The client should be updated to validate and reject any requests to create those imposters if they do not have valid key/cert.

**Comment by SuperDrew** [comment]
Good shout, I should've thought of that.

**Comment by mattherman** [comment]
I didn't realize it required it until I tried to create an HTTPS imposter with some stubs. When it attempts to submit the imposter, it will just hang on the request. It seems strange. I would have figured mountebank would just return an error. Anyways, I think the acceptance tests should be updated to include some stubs when creating imposters since right now they just create empty ones (which didn't catch this issue).
