### ISSUE TITLE
Support imposter updates/replacements

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#29]
Mountebank allows you to completely replace an existing imposter through a PUT request to the imposters resource. Since it deletes the imposter and replaces it with the new one, this can also be used to update an imposter, for example if you added a stub after already submitting it.

**Comment by mattherman** [comment]
This could either be an entirely separate client method, or a optional boolean parameter like:
```
public void Submit(Imposter imposter, bool shouldReplace = false);
```

I am leaning towards the optional param.

**Comment by jgitter** [comment]
This would be very helpful for me.  I'm going to take a stab at this one as well.

**Comment by mattherman** [comment]
I was looking at this recently and it seems like you are not able to replace a single imposter. The PUT request is to replace ALL imposters with a new set of imposters. This might be worth implementing, but it won't work the way I had hoped.

**Comment by adambeben** [comment]
It should be possible now with v2.1.0 features: "Support mutating stubs without restarting the imposter.".

**Comment by mattherman** [comment]
Yeah, looks like you are right. Leaving this here for future reference: http://www.mbtest.org/docs/api/overview#change-stubs

**Comment by mattherman** [comment]
Decided to go with a separate client method -
```
Task UpdateImposterAsync(Imposter imposter, CancellationToken cancellationToken = default)
```
