### ISSUE TITLE
Support Dynamic Ports

### ISSUE THREAD

**Issue by jgitter** [mattherman/MbDotNet#32]
Mountebank allows you to create imposters without a port.  A random port will be assigned which can then be retrieved from the POST response or a subsequent GET.   The client should also allow this as well.

**Comment by mattherman** [comment]
That is a good suggestion and would be simple to implement.

If you, or anyone else, wants to submit a PR for it, I'll take a look. Else I'll take care of this when I get some free time.

**Comment by jgitter** [comment]
I will definitely consider doing that.  Kudos for the awesome MB client!

**Comment by jgitter** [comment]
Pull Request created: https://github.com/mattherman/MbDotNet/pull/33.

Cheers!

**Comment by jgitter** [comment]
Pull request has been merged.  Closing this enhancement request.
