### ISSUE TITLE
Looks like an unusual code arrangement

### ISSUE THREAD

**Issue by michaelgwelch** [mattherman/MbDotNet#5]
Typically classes/types are arranged around functionality, not around their types (Enums, Interfaces, etc.). At least with regards to namespaces.

**Comment by lalitkale** [comment]
I will be happy to refactor the project according to namepsaces but this will be I think one big PR to merge. Any thoughts?

**Comment by mattherman** [comment]
Sure. If you want to take the time to refactor it, I don't mind. Just submit a PR and I'll take a look. Thanks.

**Comment by mattherman** [comment]
Closing after merge of #26
