### ISSUE TITLE
Expose Async methods for creating/deleting/retrieving imposters

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#51]

**Comment by mattherman** [comment]
I will likely be retiring the original synchronous methods and only exposing the new async ones. My reasoning for this is summarized in [this blog post](https://blogs.msdn.microsoft.com/pfxteam/2012/04/13/should-i-expose-synchronous-wrappers-for-asynchronous-methods/).

**Comment by putnap** [comment]
Hi,
It seems that I'm having deadlock issues when using this library in specflow tests ran by xUnit runner. Are those async methods comming soon?

Edit: I found this commit revert https://github.com/mattherman/MbDotNet/commit/a116d804e7efb74fe82357f44ad2a9b40b849aaf#diff-ff4f93627e0d86b9522cadf4862b863a

This library is using .Result which can cause deadlocks in many situations. Proper way to do it would be to expose async methods and also set the calls with .ConfigureAwait(false).

**Comment by mattherman** [comment]
I'll try to get this done some time soon. I know I had made the change previously, but I think it broke some tests for some reason and I didn't have time to resolve the issue. It is a breaking change and there were a few more things I wanted to complete before publishing a v5, but I could probably publish a pre-release version with the change when it is done.

**Comment by putnap** [comment]
Do you need some assistance with that?

**Comment by mattherman** [comment]
Sure, that would be helpful. I'll definitely have time to review a PR if you submit one.

When you make the change, just get rid of the synchronous methods, I only planned on exposing async ones after this change was complete. Also, I would prefer to follow the convention of adding "Async" to the end of the method names.

**Comment by putnap** [comment]
Created a pull request for this https://github.com/mattherman/MbDotNet/pull/60

**Comment by mattherman** [comment]
This has been resolved by #60 and published as 5.0.0-rc1
