### ISSUE TITLE
Version 4.0.0 is missing ReturnsProxy method

### ISSUE THREAD

**Issue by LeopoldoFu** [mattherman/MbDotNet#56]
I'm trying to follow the [version 4 example](https://github.com/mattherman/MbDotNet/wiki/Usage-Examples-(v4)) for proxying, but `ReturnsProxy` and a few supposed version 4 methods/classes are missing. They look like they are in master though.

**Comment by mattherman** [comment]
Sorry, I updated the docs after that feature was merged, but then I was working on a few other changes that I figured I would release in one batch. I'll try to get a v4.1.0 pushed out later today with that feature.

**Comment by mattherman** [comment]
I just uploaded the new version. It should be available for install within an hour.

**Comment by LeopoldoFu** [comment]
Thanks for the quick turnaround!
