### ISSUE TITLE
Remove `CreateXYZImposter` methods from `MountebankClient`

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#66]
There have been other breaking changes (such as removal of non-async client methods) that will require pushing a v5 of the library. Due to this, I am looking at other mistakes I've made that would require breaking changes. One of those mistakes is that addition of the `CreateXYZImposter` methods on the `MountebankClient` class that serve as factory methods for the imposters. There is no real reason why these factory methods are necessary since their signatures are essentially identical to the imposters' constructors. They also seem to confuse users since they sometimes expect those methods to have actually submitted the new imposter to mountebank.

In order to remedy this, I am considering removing them altogether and just expecting users to create the imposters themselves via the constructors.

**Comment by jzabroski** [comment]
I think AutoFixture would help give people guidance on how to generate imposters, plus add a degree of randomness.

**Comment by mattherman** [comment]
Once these methods are removed, the `Imposters` collection on `MountebankClient` will also be removed.

**Comment by mattherman** [comment]
Resolved by #111
