### ISSUE TITLE
Update client to include newer API methods

### ISSUE THREAD

**Issue by mattherman** [mattherman/MbDotNet#67]
There have been a few new API methods added to mountebank since this library was created. An issue has already been created for adding the ability to update imposters (#29) but there are a couple more that could be added. Adding this issue for a place to track that. 

Capability | Supported? | Planned | Notes
-|-|-|-
Get entry hypermedia | ✔️ |
Create a single imposter | ✔️ |
Get a single imposter | ✔️ | |
Add a stub to an existing imposter | ✔️ |
Overwrite a stub of an existing imposter | ✔️ |
Overwrite all stubs of an existing imposter | ✔️ |
Remove a stub of an existing imposter | ✔️ |
Delete a single imposter | ✔️ | |
Delete saved proxy responses from an imposter | ✔️ |
Overwrite all imposters with a new set of imposters | ❌ | ❓ | 
Get a list of all imposters | ✔️ |
Delete all imposters | ✔️ | |
Get mountebank configuration and process information | ✔️ |
Get the logs | ✔️ |

This list is up to date as of mountebank v2.8.2 and taken from [this page](www.mbtest.org/docs/api/overview).

**Comment by jzabroski** [comment]
Suggestion:
1. Create a third column called Planned?
2. Use ❌ instead of writing "No" and ✔️ instead of writing a "Yes".  It makes reading a lot easier instead of Yes/No.
3. Use 👍 and 👎 for planned/no planning, and ❓ for unsure and ☠️ for difficult due to MbDotNet architecture.

The emojis are:
```
:x:
:heavy_check_mark:
:+1:
:-1:
:skull_and_crossbones_:
:question:
```

**Comment by mattherman** [comment]
Updated.

**Comment by mattherman** [comment]
Added the ability to replace stubs of an existing imposter #76

**Comment by mattherman** [comment]
"Delete save proxy responses from an imposter" added in #82, updated table

**Comment by mattherman** [comment]
MbDotNet now supports all of the API methods Mountebank supports as of v2.8.2.

These changes will be published in MbDotNet v5 in a few days.

**Comment by jzabroski** [comment]
Great job
