### ISSUE TITLE
Add 'Exists' predicate

### ISSUE THREAD

**Issue by kiwiprog** [mattherman/MbDotNet#70]
Proposing to extend the list of possible predicates to include the [exists predicate](http://www.mbtest.org/docs/api/predicates#predicates-exists).

**Comment by MahmoudAbduo** [comment]
Proposing to extend the list of possible predicates to include the [exists predicate](http://www.mbtest.org/docs/api/predicates#predicates-exists).

**Comment by mattherman** [comment]
I think I attempted to add this at one point, but it didn't quite fit with the current way predicate fields are modeled. If you have a way to add this cleanly, please do.

**Comment by kiwiprog** [comment]
@mattherman to me it looked identical to how equals/matches work, the only difference being that it expects HttpPredicateFields with all the nodes having boolean values (indicating whether they must exist or not) instead of matching/equal values. I've left an example in the PR description and documentation tests: https://github.com/mattherman/MbDotNet/pull/72

For such usages, the code works fine and I'm not aware of other use cases for the exists predicate which do not fit with the current way predicate fields are modeled. In case I am mistaken, can you elaborate please?
