### ISSUE TITLE
Add support for form content in HttpPredicateFields

### ISSUE THREAD

**Issue by kiwiprog** [mattherman/MbDotNet#71]
When sending form content using the `application/x-www-form-urlencoded` content type, the body containing the content is a string in a form such as:

`parameter1=value1&parameter2=value2`

To intercept this with a Mountebank predicate using MbDotNet, it is possible to do the following: 

```C#
var predicate = new HttpPredicateFields
{
    RequestBody = "parameter1=value1&parameter2=value2"
};
```

However, because of the nature of form content which is created using a dictionary, we are not guaranteed that all of the parameters will be formed into a string in the order that our predicate specifies. For example:

```C#
var requestContent = new Dictionary<string, string>
{
    ["parameter1"] = "value1",
    ["parameter2"] = "value2"
};

var httpMessage = new HttpRequestMessage();
httpMessage.Content = new FormUrlEncodedContent(requestContent);
```

As per [this Mountebank PR](https://github.com/bbyars/mountebank/pull/298) and [documentation (see Http Requests)](http://www.mbtest.org/docs/protocols/http), support has been added to specify form content as key value pairs in Mountebank. In Mountebank JSON, the predicate would look like:

```JSON
{
    "matches": {
        "form": {
            "parameter1": "value1",
            "parameter2": "value2"
        },
        "headers": {
            "Content-Type": "application/x-www-form-urlencoded"
        }
    },
    "caseSensitive": false
}
```

The `HttpPredicateFields` class in MbDotNet does not currently have support to add this natively. In a project I worked on, I have been able to extend the class and add support for form content via MbDotNet successfully.

I would like to see this as part of the MbDotNet library so that others may benefit from it and I'm happy to make the PR to support this.

**Comment by mattherman** [comment]
This seems useful. Feel free to submit a PR and I'll take a look.

**Comment by kiwiprog** [comment]
PR created [here (PR #73)](https://github.com/mattherman/MbDotNet/pull/73)
