### ISSUE TITLE
Add async API to nuget package

### ISSUE THREAD

**Issue by malabarMCB** [mattherman/MbDotNet#81]
For now the last available version is 4.3.1. It doesn't contain async API methods, instead of it there are Task.Result and Task.Wait() invocations. Such approach could cause a deadlock. As I see it is fixed in the master branch, so could you please release a new nuget package with async API

**Comment by mattherman** [comment]
The async methods are available in the `v5.0.0` pre-release packages. I have not released a stable package with them yet since I have other breaking changes planned before I push the new major version.

**Comment by malabarMCB** [comment]
Ok, waiting for the major version
