### ISSUE TITLE
Question - can we mock grpc service using this?

### ISSUE THREAD

**Issue by zeeshankhan0330** [mattherman/MbDotNet#89]

**Comment by mattherman** [comment]
I don't know much about gRPC, but if it uses HTTP then you should be able to mock it using mountebank (and MbDotNet). The difficulty of doing that will depend on what the data looks like over the wire though, but Mountebank lets you [define custom protocols](http://www.mbtest.org/docs/protocols/custom) that can make it easier. In fact it looks like there is already a community plugin for gRPC:
https://github.com/cbrz/mountebank-grpc

However, MbDotNet itself (which is just a .NET wrapper around mountebank) does not support custom protocols right now. It only exposes the default imposter types (HTTP, HTTPS, TCP, and SMTP). Theoretically you could create your own `GRpcImposter` and `GRpcStub` classes that extend the appropriate base classes and use MbDotNet with the custom gRPC protocol, but these aren't something that would be added to this package. You're likely better off skipping MbDotNet and just using that custom protocol with mountebank directly.

**Comment by zeeshankhan0330** [comment]
@mattherman  thanks mathew for detailed explanation.
