### ISSUE TITLE
Support "allowCORS" Imposter Creation Parameter

### ISSUE THREAD

**Issue by tparikka** [mattherman/MbDotNet#90]
Currently there is no corresponding parameter in the HttpImposter and HttpsImposter constructors for the `allowCORS` parameter, documented here:

http://www.mbtest.org/docs/protocols/http

Is this something that could be added, and if so would the best place to add it be in the constructor as an optional parameter? I'd be happy to take a crack at it if that's the right place to introduce it.

**Comment by mattherman** [comment]
Seems like a reasonable thing to add. It would be added to the constructor alongside things like `recordRequests` and `defaultResponse`. Feel free to submit a PR if this is something that would be useful to you.
