### ISSUE TITLE
Support query parameters with the same parameter key

### ISSUE THREAD

**Issue by ghost** [mattherman/MbDotNet#97]
It is possible to have query parameters that share the same key for example: `https://example.com/get?param1=test1&param1=test2&param1=test3`

It would be nice for the client to support this as it does not currently since HttpPredicateFields : https://github.com/mattherman/MbDotNet/blob/master/MbDotNet/Models/Predicates/Fields/HttpPredicateFields.cs uses a Dictionary for query parameters.

I know this may be a little controversial since there is not set HTTP standard on how to deal with multiple parameters with the same key but it looks like Microsoft are consistent on how it is parsed for example - https://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request

One way to preserve the same outcomes without breaking changes could be to change it from a `IDictionary<string, object>` to a `IEnumerable<KeyValuePair<string, object>>`

**Comment by mattherman** [comment]
This is supported as of #80. Since it is `Dictionary<string, object>` you can set the value to an array containing each of the expected parameter values like this:
```
imposter.AddStub()
    .ReturnsBody(HttpStatusCode.OK, "matched duplicate params")
    .On(new EqualsPredicate<HttpPredicateFields>(new HttpPredicateFields
    {
        QueryParameters = new Dictionary<string, object>
        {
            ["myParam"] = new[] {1, 2}
        }
    }));
```

Let me know if this doesn't work for you for some reason.

**Comment by ghost** [comment]
Oh so you are saying that if we pass in an array of the values instead then it will translate to `....?myParam=1&myParam=2` ? If so then this should work for us and I didn't realise this would work that way. Thanks very much

**Comment by mattherman** [comment]
Yes. Your example query string would match the predicate above. Glad I could help!
